// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: foundation.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAudit = `-- name: AppendAudit :exec
INSERT INTO audit_records (tenant_id,event_id,event_type,occurred_at,actor_type,actor_id,request_id,trace_id,resource_type,resource_id,previous_state,new_state,safe_reason_code,source_component,intent_id,intent_version,intent_digest,approval_id,policy_id,policy_version,policy_decision,policy_evaluation_key,execution_id,execution_revision,execution_request_id,execution_request_key,execution_status,recovery_reason_code,wallet_binding_id,wallet_binding_version,user_id,operation_key,operation_version)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33)
`

type AppendAuditParams struct {
	TenantID             string             `json:"tenant_id"`
	EventID              string             `json:"event_id"`
	EventType            string             `json:"event_type"`
	OccurredAt           pgtype.Timestamptz `json:"occurred_at"`
	ActorType            string             `json:"actor_type"`
	ActorID              string             `json:"actor_id"`
	RequestID            string             `json:"request_id"`
	TraceID              string             `json:"trace_id"`
	ResourceType         string             `json:"resource_type"`
	ResourceID           string             `json:"resource_id"`
	PreviousState        string             `json:"previous_state"`
	NewState             string             `json:"new_state"`
	SafeReasonCode       string             `json:"safe_reason_code"`
	SourceComponent      string             `json:"source_component"`
	IntentID             string             `json:"intent_id"`
	IntentVersion        int64              `json:"intent_version"`
	IntentDigest         string             `json:"intent_digest"`
	ApprovalID           string             `json:"approval_id"`
	PolicyID             string             `json:"policy_id"`
	PolicyVersion        int64              `json:"policy_version"`
	PolicyDecision       string             `json:"policy_decision"`
	PolicyEvaluationKey  string             `json:"policy_evaluation_key"`
	ExecutionID          string             `json:"execution_id"`
	ExecutionRevision    int64              `json:"execution_revision"`
	ExecutionRequestID   string             `json:"execution_request_id"`
	ExecutionRequestKey  string             `json:"execution_request_key"`
	ExecutionStatus      string             `json:"execution_status"`
	RecoveryReasonCode   string             `json:"recovery_reason_code"`
	WalletBindingID      string             `json:"wallet_binding_id"`
	WalletBindingVersion int64              `json:"wallet_binding_version"`
	UserID               string             `json:"user_id"`
	OperationKey         string             `json:"operation_key"`
	OperationVersion     int64              `json:"operation_version"`
}

func (q *Queries) AppendAudit(ctx context.Context, arg AppendAuditParams) error {
	_, err := q.db.Exec(ctx, appendAudit,
		arg.TenantID,
		arg.EventID,
		arg.EventType,
		arg.OccurredAt,
		arg.ActorType,
		arg.ActorID,
		arg.RequestID,
		arg.TraceID,
		arg.ResourceType,
		arg.ResourceID,
		arg.PreviousState,
		arg.NewState,
		arg.SafeReasonCode,
		arg.SourceComponent,
		arg.IntentID,
		arg.IntentVersion,
		arg.IntentDigest,
		arg.ApprovalID,
		arg.PolicyID,
		arg.PolicyVersion,
		arg.PolicyDecision,
		arg.PolicyEvaluationKey,
		arg.ExecutionID,
		arg.ExecutionRevision,
		arg.ExecutionRequestID,
		arg.ExecutionRequestKey,
		arg.ExecutionStatus,
		arg.RecoveryReasonCode,
		arg.WalletBindingID,
		arg.WalletBindingVersion,
		arg.UserID,
		arg.OperationKey,
		arg.OperationVersion,
	)
	return err
}

const appendVerificationEvidence = `-- name: AppendVerificationEvidence :execrows
INSERT INTO verification_evidence (tenant_id,execution_id,execution_version,status,adapter_reference,error_code,observed_at)
SELECT $1,$2,$3,$4,$5,$6,$7
FROM executions e JOIN execution_requests r ON r.tenant_id=e.tenant_id AND r.request_id=e.request_id
WHERE e.tenant_id=$1 AND e.execution_id=$2 AND e.revision=$3 AND e.status=$4 AND r.user_id=$8
`

type AppendVerificationEvidenceParams struct {
	TenantID         string             `json:"tenant_id"`
	ExecutionID      string             `json:"execution_id"`
	ExecutionVersion int64              `json:"execution_version"`
	Status           string             `json:"status"`
	AdapterReference string             `json:"adapter_reference"`
	ErrorCode        string             `json:"error_code"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	ActorID          string             `json:"actor_id"`
}

func (q *Queries) AppendVerificationEvidence(ctx context.Context, arg AppendVerificationEvidenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, appendVerificationEvidence,
		arg.TenantID,
		arg.ExecutionID,
		arg.ExecutionVersion,
		arg.Status,
		arg.AdapterReference,
		arg.ErrorCode,
		arg.ObservedAt,
		arg.ActorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (tenant_id,approval_id,approval_version,approval_request_id,intent_id,intent_version,intent_digest,user_id,wallet_binding_id,wallet_binding_version,wallet_id,wallet_address,chain_id,status,decision,created_at,expires_at,decided_at,consumed_at,operation_key,operation_version,lifecycle_version)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)
RETURNING tenant_id, approval_id, approval_version, approval_request_id, intent_id, intent_version, intent_digest, user_id, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, status, decision, created_at, expires_at, decided_at, consumed_at, operation_key, operation_version, lifecycle_version
`

type CreateApprovalParams struct {
	TenantID             string             `json:"tenant_id"`
	ApprovalID           string             `json:"approval_id"`
	ApprovalVersion      int64              `json:"approval_version"`
	ApprovalRequestID    string             `json:"approval_request_id"`
	IntentID             string             `json:"intent_id"`
	IntentVersion        int64              `json:"intent_version"`
	IntentDigest         string             `json:"intent_digest"`
	UserID               string             `json:"user_id"`
	WalletBindingID      string             `json:"wallet_binding_id"`
	WalletBindingVersion int64              `json:"wallet_binding_version"`
	WalletID             string             `json:"wallet_id"`
	WalletAddress        string             `json:"wallet_address"`
	ChainID              string             `json:"chain_id"`
	Status               string             `json:"status"`
	Decision             string             `json:"decision"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	DecidedAt            pgtype.Timestamptz `json:"decided_at"`
	ConsumedAt           pgtype.Timestamptz `json:"consumed_at"`
	OperationKey         *string            `json:"operation_key"`
	OperationVersion     *int64             `json:"operation_version"`
	LifecycleVersion     int64              `json:"lifecycle_version"`
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.TenantID,
		arg.ApprovalID,
		arg.ApprovalVersion,
		arg.ApprovalRequestID,
		arg.IntentID,
		arg.IntentVersion,
		arg.IntentDigest,
		arg.UserID,
		arg.WalletBindingID,
		arg.WalletBindingVersion,
		arg.WalletID,
		arg.WalletAddress,
		arg.ChainID,
		arg.Status,
		arg.Decision,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.DecidedAt,
		arg.ConsumedAt,
		arg.OperationKey,
		arg.OperationVersion,
		arg.LifecycleVersion,
	)
	var i Approval
	err := row.Scan(
		&i.TenantID,
		&i.ApprovalID,
		&i.ApprovalVersion,
		&i.ApprovalRequestID,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.UserID,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Status,
		&i.Decision,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.ConsumedAt,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (tenant_id,execution_id,request_id,status,revision,created_at,updated_at,failure_code,failure_eligibility,failure_recovery_target,failed_from_status,recovery_reason_code,recovery_from_status,recovery_target_status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING tenant_id, execution_id, request_id, status, revision, created_at, updated_at, failure_code, failure_eligibility, failure_recovery_target, failed_from_status, recovery_reason_code, recovery_from_status, recovery_target_status
`

type CreateExecutionParams struct {
	TenantID              string             `json:"tenant_id"`
	ExecutionID           string             `json:"execution_id"`
	RequestID             string             `json:"request_id"`
	Status                string             `json:"status"`
	Revision              int64              `json:"revision"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FailureCode           string             `json:"failure_code"`
	FailureEligibility    string             `json:"failure_eligibility"`
	FailureRecoveryTarget string             `json:"failure_recovery_target"`
	FailedFromStatus      string             `json:"failed_from_status"`
	RecoveryReasonCode    string             `json:"recovery_reason_code"`
	RecoveryFromStatus    string             `json:"recovery_from_status"`
	RecoveryTargetStatus  string             `json:"recovery_target_status"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.TenantID,
		arg.ExecutionID,
		arg.RequestID,
		arg.Status,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FailureCode,
		arg.FailureEligibility,
		arg.FailureRecoveryTarget,
		arg.FailedFromStatus,
		arg.RecoveryReasonCode,
		arg.RecoveryFromStatus,
		arg.RecoveryTargetStatus,
	)
	var i Execution
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.RequestID,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureCode,
		&i.FailureEligibility,
		&i.FailureRecoveryTarget,
		&i.FailedFromStatus,
		&i.RecoveryReasonCode,
		&i.RecoveryFromStatus,
		&i.RecoveryTargetStatus,
	)
	return i, err
}

const createExecutionRequest = `-- name: CreateExecutionRequest :one
INSERT INTO execution_requests (tenant_id,request_id,request_key,request_version,execution_id,operation_key,operation_version,intent_id,intent_version,intent_digest,approval_id,approval_version,user_id,policy_id,policy_version,policy_evaluation_key,policy_evaluation_stage,policy_evaluated_at,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
RETURNING tenant_id, request_id, request_key, request_version, execution_id, operation_key, operation_version, intent_id, intent_version, intent_digest, approval_id, approval_version, user_id, policy_id, policy_version, policy_evaluation_key, policy_evaluation_stage, policy_evaluated_at, created_at
`

type CreateExecutionRequestParams struct {
	TenantID              string             `json:"tenant_id"`
	RequestID             string             `json:"request_id"`
	RequestKey            string             `json:"request_key"`
	RequestVersion        int64              `json:"request_version"`
	ExecutionID           string             `json:"execution_id"`
	OperationKey          string             `json:"operation_key"`
	OperationVersion      int64              `json:"operation_version"`
	IntentID              string             `json:"intent_id"`
	IntentVersion         int64              `json:"intent_version"`
	IntentDigest          string             `json:"intent_digest"`
	ApprovalID            string             `json:"approval_id"`
	ApprovalVersion       int64              `json:"approval_version"`
	UserID                string             `json:"user_id"`
	PolicyID              string             `json:"policy_id"`
	PolicyVersion         int64              `json:"policy_version"`
	PolicyEvaluationKey   string             `json:"policy_evaluation_key"`
	PolicyEvaluationStage string             `json:"policy_evaluation_stage"`
	PolicyEvaluatedAt     pgtype.Timestamptz `json:"policy_evaluated_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateExecutionRequest(ctx context.Context, arg CreateExecutionRequestParams) (ExecutionRequest, error) {
	row := q.db.QueryRow(ctx, createExecutionRequest,
		arg.TenantID,
		arg.RequestID,
		arg.RequestKey,
		arg.RequestVersion,
		arg.ExecutionID,
		arg.OperationKey,
		arg.OperationVersion,
		arg.IntentID,
		arg.IntentVersion,
		arg.IntentDigest,
		arg.ApprovalID,
		arg.ApprovalVersion,
		arg.UserID,
		arg.PolicyID,
		arg.PolicyVersion,
		arg.PolicyEvaluationKey,
		arg.PolicyEvaluationStage,
		arg.PolicyEvaluatedAt,
		arg.CreatedAt,
	)
	var i ExecutionRequest
	err := row.Scan(
		&i.TenantID,
		&i.RequestID,
		&i.RequestKey,
		&i.RequestVersion,
		&i.ExecutionID,
		&i.OperationKey,
		&i.OperationVersion,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.ApprovalID,
		&i.ApprovalVersion,
		&i.UserID,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.PolicyEvaluationKey,
		&i.PolicyEvaluationStage,
		&i.PolicyEvaluatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (tenant_id, user_id, provider, provider_subject, status, lifecycle_version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 1, $6, $6)
RETURNING tenant_id, user_id, provider, status, lifecycle_version, created_at, updated_at, provider_subject
`

type CreateIdentityParams struct {
	TenantID        string             `json:"tenant_id"`
	UserID          string             `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.TenantID,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Status,
		arg.CreatedAt,
	)
	var i Identity
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.LifecycleVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderSubject,
	)
	return i, err
}

const createIntent = `-- name: CreateIntent :one
INSERT INTO intents (tenant_id,intent_id,intent_version,client_request_id,nonce,intent_type,user_id,identity_provider,provider_user_reference,wallet_binding_id,wallet_binding_version,wallet_id,wallet_address,chain_id,network,financial,route_type,route_reference,route_version,constraint_deadline,policy_reference,created_at,expires_at,status,intent_digest,operation_key,operation_version,lifecycle_version)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28)
RETURNING tenant_id, intent_id, intent_version, client_request_id, nonce, intent_type, user_id, identity_provider, provider_user_reference, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, network, financial, route_type, route_reference, route_version, constraint_deadline, policy_reference, created_at, expires_at, status, intent_digest, operation_key, operation_version, lifecycle_version
`

type CreateIntentParams struct {
	TenantID              string             `json:"tenant_id"`
	IntentID              string             `json:"intent_id"`
	IntentVersion         int64              `json:"intent_version"`
	ClientRequestID       string             `json:"client_request_id"`
	Nonce                 string             `json:"nonce"`
	IntentType            string             `json:"intent_type"`
	UserID                string             `json:"user_id"`
	IdentityProvider      string             `json:"identity_provider"`
	ProviderUserReference string             `json:"provider_user_reference"`
	WalletBindingID       string             `json:"wallet_binding_id"`
	WalletBindingVersion  int64              `json:"wallet_binding_version"`
	WalletID              string             `json:"wallet_id"`
	WalletAddress         string             `json:"wallet_address"`
	ChainID               string             `json:"chain_id"`
	Network               string             `json:"network"`
	Financial             []byte             `json:"financial"`
	RouteType             string             `json:"route_type"`
	RouteReference        string             `json:"route_reference"`
	RouteVersion          int64              `json:"route_version"`
	ConstraintDeadline    pgtype.Timestamptz `json:"constraint_deadline"`
	PolicyReference       string             `json:"policy_reference"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	Status                string             `json:"status"`
	IntentDigest          *string            `json:"intent_digest"`
	OperationKey          *string            `json:"operation_key"`
	OperationVersion      *int64             `json:"operation_version"`
	LifecycleVersion      int64              `json:"lifecycle_version"`
}

func (q *Queries) CreateIntent(ctx context.Context, arg CreateIntentParams) (Intent, error) {
	row := q.db.QueryRow(ctx, createIntent,
		arg.TenantID,
		arg.IntentID,
		arg.IntentVersion,
		arg.ClientRequestID,
		arg.Nonce,
		arg.IntentType,
		arg.UserID,
		arg.IdentityProvider,
		arg.ProviderUserReference,
		arg.WalletBindingID,
		arg.WalletBindingVersion,
		arg.WalletID,
		arg.WalletAddress,
		arg.ChainID,
		arg.Network,
		arg.Financial,
		arg.RouteType,
		arg.RouteReference,
		arg.RouteVersion,
		arg.ConstraintDeadline,
		arg.PolicyReference,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Status,
		arg.IntentDigest,
		arg.OperationKey,
		arg.OperationVersion,
		arg.LifecycleVersion,
	)
	var i Intent
	err := row.Scan(
		&i.TenantID,
		&i.IntentID,
		&i.IntentVersion,
		&i.ClientRequestID,
		&i.Nonce,
		&i.IntentType,
		&i.UserID,
		&i.IdentityProvider,
		&i.ProviderUserReference,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Network,
		&i.Financial,
		&i.RouteType,
		&i.RouteReference,
		&i.RouteVersion,
		&i.ConstraintDeadline,
		&i.PolicyReference,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.IntentDigest,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (tenant_id,policy_id,policy_version,name,user_id,wallet_binding_id,intent_types,rules,status,created_at,valid_from,expires_at,lifecycle_version)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING tenant_id, policy_id, policy_version, name, user_id, wallet_binding_id, intent_types, rules, status, created_at, valid_from, expires_at, lifecycle_version
`

type CreatePolicyParams struct {
	TenantID         string             `json:"tenant_id"`
	PolicyID         string             `json:"policy_id"`
	PolicyVersion    int64              `json:"policy_version"`
	Name             string             `json:"name"`
	UserID           string             `json:"user_id"`
	WalletBindingID  *string            `json:"wallet_binding_id"`
	IntentTypes      []string           `json:"intent_types"`
	Rules            []byte             `json:"rules"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LifecycleVersion int64              `json:"lifecycle_version"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.TenantID,
		arg.PolicyID,
		arg.PolicyVersion,
		arg.Name,
		arg.UserID,
		arg.WalletBindingID,
		arg.IntentTypes,
		arg.Rules,
		arg.Status,
		arg.CreatedAt,
		arg.ValidFrom,
		arg.ExpiresAt,
		arg.LifecycleVersion,
	)
	var i Policy
	err := row.Scan(
		&i.TenantID,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.Name,
		&i.UserID,
		&i.WalletBindingID,
		&i.IntentTypes,
		&i.Rules,
		&i.Status,
		&i.CreatedAt,
		&i.ValidFrom,
		&i.ExpiresAt,
		&i.LifecycleVersion,
	)
	return i, err
}

const createPolicyEvaluation = `-- name: CreatePolicyEvaluation :one
INSERT INTO policy_evaluations (tenant_id,evaluation_key,policy_id,policy_version,user_id,intent_id,intent_version,intent_digest,stage,decision,evaluated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING tenant_id, evaluation_key, policy_id, policy_version, user_id, intent_id, intent_version, intent_digest, stage, decision, evaluated_at
`

type CreatePolicyEvaluationParams struct {
	TenantID      string             `json:"tenant_id"`
	EvaluationKey string             `json:"evaluation_key"`
	PolicyID      string             `json:"policy_id"`
	PolicyVersion int64              `json:"policy_version"`
	UserID        string             `json:"user_id"`
	IntentID      string             `json:"intent_id"`
	IntentVersion int64              `json:"intent_version"`
	IntentDigest  string             `json:"intent_digest"`
	Stage         string             `json:"stage"`
	Decision      string             `json:"decision"`
	EvaluatedAt   pgtype.Timestamptz `json:"evaluated_at"`
}

func (q *Queries) CreatePolicyEvaluation(ctx context.Context, arg CreatePolicyEvaluationParams) (PolicyEvaluation, error) {
	row := q.db.QueryRow(ctx, createPolicyEvaluation,
		arg.TenantID,
		arg.EvaluationKey,
		arg.PolicyID,
		arg.PolicyVersion,
		arg.UserID,
		arg.IntentID,
		arg.IntentVersion,
		arg.IntentDigest,
		arg.Stage,
		arg.Decision,
		arg.EvaluatedAt,
	)
	var i PolicyEvaluation
	err := row.Scan(
		&i.TenantID,
		&i.EvaluationKey,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.UserID,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.Stage,
		&i.Decision,
		&i.EvaluatedAt,
	)
	return i, err
}

const createPolicyFinding = `-- name: CreatePolicyFinding :exec
INSERT INTO policy_evaluation_findings (tenant_id,evaluation_key,finding_index,rule_id,rule_type,decision,reason)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (tenant_id,evaluation_key,finding_index) DO NOTHING
`

type CreatePolicyFindingParams struct {
	TenantID      string `json:"tenant_id"`
	EvaluationKey string `json:"evaluation_key"`
	FindingIndex  int32  `json:"finding_index"`
	RuleID        string `json:"rule_id"`
	RuleType      string `json:"rule_type"`
	Decision      string `json:"decision"`
	Reason        string `json:"reason"`
}

func (q *Queries) CreatePolicyFinding(ctx context.Context, arg CreatePolicyFindingParams) error {
	_, err := q.db.Exec(ctx, createPolicyFinding,
		arg.TenantID,
		arg.EvaluationKey,
		arg.FindingIndex,
		arg.RuleID,
		arg.RuleType,
		arg.Decision,
		arg.Reason,
	)
	return err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (tenant_id, created_at) VALUES ($1, $2)
ON CONFLICT (tenant_id) DO UPDATE SET tenant_id = EXCLUDED.tenant_id
RETURNING tenant_id, created_at
`

type CreateTenantParams struct {
	TenantID  string             `json:"tenant_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.TenantID, arg.CreatedAt)
	var i Tenant
	err := row.Scan(&i.TenantID, &i.CreatedAt)
	return i, err
}

const createWalletBinding = `-- name: CreateWalletBinding :one
INSERT INTO wallet_bindings (tenant_id, binding_id, version, user_id, provider, provider_user_reference, wallet_id, address, chain_id, network, status, verification_reference, created_at, verified_at, revoked_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
RETURNING tenant_id, binding_id, version, user_id, provider, provider_user_reference, wallet_id, address, chain_id, network, status, verification_reference, created_at, verified_at, revoked_at
`

type CreateWalletBindingParams struct {
	TenantID              string             `json:"tenant_id"`
	BindingID             string             `json:"binding_id"`
	Version               int64              `json:"version"`
	UserID                string             `json:"user_id"`
	Provider              string             `json:"provider"`
	ProviderUserReference string             `json:"provider_user_reference"`
	WalletID              string             `json:"wallet_id"`
	Address               string             `json:"address"`
	ChainID               string             `json:"chain_id"`
	Network               string             `json:"network"`
	Status                string             `json:"status"`
	VerificationReference string             `json:"verification_reference"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	VerifiedAt            pgtype.Timestamptz `json:"verified_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) CreateWalletBinding(ctx context.Context, arg CreateWalletBindingParams) (WalletBinding, error) {
	row := q.db.QueryRow(ctx, createWalletBinding,
		arg.TenantID,
		arg.BindingID,
		arg.Version,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserReference,
		arg.WalletID,
		arg.Address,
		arg.ChainID,
		arg.Network,
		arg.Status,
		arg.VerificationReference,
		arg.CreatedAt,
		arg.VerifiedAt,
		arg.RevokedAt,
	)
	var i WalletBinding
	err := row.Scan(
		&i.TenantID,
		&i.BindingID,
		&i.Version,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserReference,
		&i.WalletID,
		&i.Address,
		&i.ChainID,
		&i.Network,
		&i.Status,
		&i.VerificationReference,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findApplicablePolicies = `-- name: FindApplicablePolicies :many
WITH current_versions AS (
  SELECT DISTINCT ON (tenant_id, policy_id) tenant_id, policy_id, policy_version, name, user_id, wallet_binding_id, intent_types, rules, status, created_at, valid_from, expires_at, lifecycle_version FROM policies
  WHERE tenant_id=$1
  ORDER BY tenant_id, policy_id, policy_version DESC
)
SELECT tenant_id, policy_id, policy_version, name, user_id, wallet_binding_id, intent_types, rules, status, created_at, valid_from, expires_at, lifecycle_version FROM current_versions
WHERE user_id=$2 AND (wallet_binding_id IS NULL OR wallet_binding_id=$3)
  AND (cardinality(intent_types)=0 OR $4::text = ANY(intent_types))
  AND status='ACTIVE' AND valid_from <= $5::timestamptz
  AND expires_at > $5::timestamptz
ORDER BY policy_id, policy_version
`

type FindApplicablePoliciesParams struct {
	TenantID        string             `json:"tenant_id"`
	UserID          string             `json:"user_id"`
	WalletBindingID *string            `json:"wallet_binding_id"`
	IntentType      string             `json:"intent_type"`
	EvaluatedAt     pgtype.Timestamptz `json:"evaluated_at"`
}

type FindApplicablePoliciesRow struct {
	TenantID         string             `json:"tenant_id"`
	PolicyID         string             `json:"policy_id"`
	PolicyVersion    int64              `json:"policy_version"`
	Name             string             `json:"name"`
	UserID           string             `json:"user_id"`
	WalletBindingID  *string            `json:"wallet_binding_id"`
	IntentTypes      []string           `json:"intent_types"`
	Rules            []byte             `json:"rules"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LifecycleVersion int64              `json:"lifecycle_version"`
}

func (q *Queries) FindApplicablePolicies(ctx context.Context, arg FindApplicablePoliciesParams) ([]FindApplicablePoliciesRow, error) {
	rows, err := q.db.Query(ctx, findApplicablePolicies,
		arg.TenantID,
		arg.UserID,
		arg.WalletBindingID,
		arg.IntentType,
		arg.EvaluatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindApplicablePoliciesRow{}
	for rows.Next() {
		var i FindApplicablePoliciesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.PolicyID,
			&i.PolicyVersion,
			&i.Name,
			&i.UserID,
			&i.WalletBindingID,
			&i.IntentTypes,
			&i.Rules,
			&i.Status,
			&i.CreatedAt,
			&i.ValidFrom,
			&i.ExpiresAt,
			&i.LifecycleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findApprovalByID = `-- name: FindApprovalByID :one
SELECT tenant_id, approval_id, approval_version, approval_request_id, intent_id, intent_version, intent_digest, user_id, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, status, decision, created_at, expires_at, decided_at, consumed_at, operation_key, operation_version, lifecycle_version FROM approvals WHERE tenant_id=$1 AND approval_id=$2 AND user_id=$3
`

type FindApprovalByIDParams struct {
	TenantID   string `json:"tenant_id"`
	ApprovalID string `json:"approval_id"`
	ActorID    string `json:"actor_id"`
}

func (q *Queries) FindApprovalByID(ctx context.Context, arg FindApprovalByIDParams) (Approval, error) {
	row := q.db.QueryRow(ctx, findApprovalByID, arg.TenantID, arg.ApprovalID, arg.ActorID)
	var i Approval
	err := row.Scan(
		&i.TenantID,
		&i.ApprovalID,
		&i.ApprovalVersion,
		&i.ApprovalRequestID,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.UserID,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Status,
		&i.Decision,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.ConsumedAt,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const findApprovalByIntent = `-- name: FindApprovalByIntent :one
SELECT tenant_id, approval_id, approval_version, approval_request_id, intent_id, intent_version, intent_digest, user_id, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, status, decision, created_at, expires_at, decided_at, consumed_at, operation_key, operation_version, lifecycle_version FROM approvals WHERE tenant_id=$1 AND intent_id=$2 AND intent_version=$3 AND intent_digest=$4 AND user_id=$5
`

type FindApprovalByIntentParams struct {
	TenantID      string `json:"tenant_id"`
	IntentID      string `json:"intent_id"`
	IntentVersion int64  `json:"intent_version"`
	IntentDigest  string `json:"intent_digest"`
	ActorID       string `json:"actor_id"`
}

func (q *Queries) FindApprovalByIntent(ctx context.Context, arg FindApprovalByIntentParams) (Approval, error) {
	row := q.db.QueryRow(ctx, findApprovalByIntent,
		arg.TenantID,
		arg.IntentID,
		arg.IntentVersion,
		arg.IntentDigest,
		arg.ActorID,
	)
	var i Approval
	err := row.Scan(
		&i.TenantID,
		&i.ApprovalID,
		&i.ApprovalVersion,
		&i.ApprovalRequestID,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.UserID,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Status,
		&i.Decision,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.ConsumedAt,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const findAuditByResource = `-- name: FindAuditByResource :many
SELECT tenant_id, event_id, event_type, occurred_at, actor_type, actor_id, request_id, trace_id, resource_type, resource_id, previous_state, new_state, safe_reason_code, source_component, intent_id, intent_version, intent_digest, approval_id, policy_id, policy_version, policy_decision, policy_evaluation_key, execution_id, execution_revision, execution_request_id, execution_request_key, execution_status, recovery_reason_code, wallet_binding_id, wallet_binding_version, user_id, operation_key, operation_version FROM audit_records WHERE tenant_id=$1 AND resource_type=$2 AND resource_id=$3 ORDER BY occurred_at,event_id
`

type FindAuditByResourceParams struct {
	TenantID     string `json:"tenant_id"`
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
}

func (q *Queries) FindAuditByResource(ctx context.Context, arg FindAuditByResourceParams) ([]AuditRecord, error) {
	rows, err := q.db.Query(ctx, findAuditByResource, arg.TenantID, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditRecord{}
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.TenantID,
			&i.EventID,
			&i.EventType,
			&i.OccurredAt,
			&i.ActorType,
			&i.ActorID,
			&i.RequestID,
			&i.TraceID,
			&i.ResourceType,
			&i.ResourceID,
			&i.PreviousState,
			&i.NewState,
			&i.SafeReasonCode,
			&i.SourceComponent,
			&i.IntentID,
			&i.IntentVersion,
			&i.IntentDigest,
			&i.ApprovalID,
			&i.PolicyID,
			&i.PolicyVersion,
			&i.PolicyDecision,
			&i.PolicyEvaluationKey,
			&i.ExecutionID,
			&i.ExecutionRevision,
			&i.ExecutionRequestID,
			&i.ExecutionRequestKey,
			&i.ExecutionStatus,
			&i.RecoveryReasonCode,
			&i.WalletBindingID,
			&i.WalletBindingVersion,
			&i.UserID,
			&i.OperationKey,
			&i.OperationVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExecutionByID = `-- name: FindExecutionByID :one
SELECT e.tenant_id, e.execution_id, e.request_id, e.status, e.revision, e.created_at, e.updated_at, e.failure_code, e.failure_eligibility, e.failure_recovery_target, e.failed_from_status, e.recovery_reason_code, e.recovery_from_status, e.recovery_target_status, r.request_key, r.request_version, r.operation_key, r.operation_version, r.intent_id, r.intent_version, r.intent_digest, r.approval_id, r.approval_version, r.policy_id, r.policy_version, r.policy_evaluation_key, r.policy_evaluation_stage, r.policy_evaluated_at, r.created_at AS request_created_at
FROM executions e JOIN execution_requests r USING (tenant_id, request_id)
WHERE e.tenant_id=$1 AND e.execution_id=$2 AND r.user_id=$3
`

type FindExecutionByIDParams struct {
	TenantID    string `json:"tenant_id"`
	ExecutionID string `json:"execution_id"`
	ActorID     string `json:"actor_id"`
}

type FindExecutionByIDRow struct {
	TenantID              string             `json:"tenant_id"`
	ExecutionID           string             `json:"execution_id"`
	RequestID             string             `json:"request_id"`
	Status                string             `json:"status"`
	Revision              int64              `json:"revision"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FailureCode           string             `json:"failure_code"`
	FailureEligibility    string             `json:"failure_eligibility"`
	FailureRecoveryTarget string             `json:"failure_recovery_target"`
	FailedFromStatus      string             `json:"failed_from_status"`
	RecoveryReasonCode    string             `json:"recovery_reason_code"`
	RecoveryFromStatus    string             `json:"recovery_from_status"`
	RecoveryTargetStatus  string             `json:"recovery_target_status"`
	RequestKey            string             `json:"request_key"`
	RequestVersion        int64              `json:"request_version"`
	OperationKey          string             `json:"operation_key"`
	OperationVersion      int64              `json:"operation_version"`
	IntentID              string             `json:"intent_id"`
	IntentVersion         int64              `json:"intent_version"`
	IntentDigest          string             `json:"intent_digest"`
	ApprovalID            string             `json:"approval_id"`
	ApprovalVersion       int64              `json:"approval_version"`
	PolicyID              string             `json:"policy_id"`
	PolicyVersion         int64              `json:"policy_version"`
	PolicyEvaluationKey   string             `json:"policy_evaluation_key"`
	PolicyEvaluationStage string             `json:"policy_evaluation_stage"`
	PolicyEvaluatedAt     pgtype.Timestamptz `json:"policy_evaluated_at"`
	RequestCreatedAt      pgtype.Timestamptz `json:"request_created_at"`
}

func (q *Queries) FindExecutionByID(ctx context.Context, arg FindExecutionByIDParams) (FindExecutionByIDRow, error) {
	row := q.db.QueryRow(ctx, findExecutionByID, arg.TenantID, arg.ExecutionID, arg.ActorID)
	var i FindExecutionByIDRow
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.RequestID,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureCode,
		&i.FailureEligibility,
		&i.FailureRecoveryTarget,
		&i.FailedFromStatus,
		&i.RecoveryReasonCode,
		&i.RecoveryFromStatus,
		&i.RecoveryTargetStatus,
		&i.RequestKey,
		&i.RequestVersion,
		&i.OperationKey,
		&i.OperationVersion,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.ApprovalID,
		&i.ApprovalVersion,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.PolicyEvaluationKey,
		&i.PolicyEvaluationStage,
		&i.PolicyEvaluatedAt,
		&i.RequestCreatedAt,
	)
	return i, err
}

const findExecutionByOperationKey = `-- name: FindExecutionByOperationKey :one
SELECT e.tenant_id, e.execution_id, e.request_id, e.status, e.revision, e.created_at, e.updated_at, e.failure_code, e.failure_eligibility, e.failure_recovery_target, e.failed_from_status, e.recovery_reason_code, e.recovery_from_status, e.recovery_target_status, r.request_key, r.request_version, r.operation_key, r.operation_version, r.intent_id, r.intent_version, r.intent_digest, r.approval_id, r.approval_version, r.policy_id, r.policy_version, r.policy_evaluation_key, r.policy_evaluation_stage, r.policy_evaluated_at, r.created_at AS request_created_at
FROM executions e JOIN execution_requests r USING (tenant_id, request_id)
WHERE e.tenant_id=$1 AND r.operation_key=$2 AND r.operation_version=$3 AND r.user_id=$4
`

type FindExecutionByOperationKeyParams struct {
	TenantID         string `json:"tenant_id"`
	OperationKey     string `json:"operation_key"`
	OperationVersion int64  `json:"operation_version"`
	ActorID          string `json:"actor_id"`
}

type FindExecutionByOperationKeyRow struct {
	TenantID              string             `json:"tenant_id"`
	ExecutionID           string             `json:"execution_id"`
	RequestID             string             `json:"request_id"`
	Status                string             `json:"status"`
	Revision              int64              `json:"revision"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FailureCode           string             `json:"failure_code"`
	FailureEligibility    string             `json:"failure_eligibility"`
	FailureRecoveryTarget string             `json:"failure_recovery_target"`
	FailedFromStatus      string             `json:"failed_from_status"`
	RecoveryReasonCode    string             `json:"recovery_reason_code"`
	RecoveryFromStatus    string             `json:"recovery_from_status"`
	RecoveryTargetStatus  string             `json:"recovery_target_status"`
	RequestKey            string             `json:"request_key"`
	RequestVersion        int64              `json:"request_version"`
	OperationKey          string             `json:"operation_key"`
	OperationVersion      int64              `json:"operation_version"`
	IntentID              string             `json:"intent_id"`
	IntentVersion         int64              `json:"intent_version"`
	IntentDigest          string             `json:"intent_digest"`
	ApprovalID            string             `json:"approval_id"`
	ApprovalVersion       int64              `json:"approval_version"`
	PolicyID              string             `json:"policy_id"`
	PolicyVersion         int64              `json:"policy_version"`
	PolicyEvaluationKey   string             `json:"policy_evaluation_key"`
	PolicyEvaluationStage string             `json:"policy_evaluation_stage"`
	PolicyEvaluatedAt     pgtype.Timestamptz `json:"policy_evaluated_at"`
	RequestCreatedAt      pgtype.Timestamptz `json:"request_created_at"`
}

func (q *Queries) FindExecutionByOperationKey(ctx context.Context, arg FindExecutionByOperationKeyParams) (FindExecutionByOperationKeyRow, error) {
	row := q.db.QueryRow(ctx, findExecutionByOperationKey,
		arg.TenantID,
		arg.OperationKey,
		arg.OperationVersion,
		arg.ActorID,
	)
	var i FindExecutionByOperationKeyRow
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.RequestID,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureCode,
		&i.FailureEligibility,
		&i.FailureRecoveryTarget,
		&i.FailedFromStatus,
		&i.RecoveryReasonCode,
		&i.RecoveryFromStatus,
		&i.RecoveryTargetStatus,
		&i.RequestKey,
		&i.RequestVersion,
		&i.OperationKey,
		&i.OperationVersion,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.ApprovalID,
		&i.ApprovalVersion,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.PolicyEvaluationKey,
		&i.PolicyEvaluationStage,
		&i.PolicyEvaluatedAt,
		&i.RequestCreatedAt,
	)
	return i, err
}

const findExecutionByRequestKey = `-- name: FindExecutionByRequestKey :one
SELECT e.tenant_id, e.execution_id, e.request_id, e.status, e.revision, e.created_at, e.updated_at, e.failure_code, e.failure_eligibility, e.failure_recovery_target, e.failed_from_status, e.recovery_reason_code, e.recovery_from_status, e.recovery_target_status, r.request_key, r.request_version, r.operation_key, r.operation_version, r.intent_id, r.intent_version, r.intent_digest, r.approval_id, r.approval_version, r.policy_id, r.policy_version, r.policy_evaluation_key, r.policy_evaluation_stage, r.policy_evaluated_at, r.created_at AS request_created_at
FROM executions e JOIN execution_requests r USING (tenant_id, request_id)
WHERE e.tenant_id=$1 AND r.request_key=$2 AND r.request_version=$3 AND r.user_id=$4
`

type FindExecutionByRequestKeyParams struct {
	TenantID       string `json:"tenant_id"`
	RequestKey     string `json:"request_key"`
	RequestVersion int64  `json:"request_version"`
	ActorID        string `json:"actor_id"`
}

type FindExecutionByRequestKeyRow struct {
	TenantID              string             `json:"tenant_id"`
	ExecutionID           string             `json:"execution_id"`
	RequestID             string             `json:"request_id"`
	Status                string             `json:"status"`
	Revision              int64              `json:"revision"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FailureCode           string             `json:"failure_code"`
	FailureEligibility    string             `json:"failure_eligibility"`
	FailureRecoveryTarget string             `json:"failure_recovery_target"`
	FailedFromStatus      string             `json:"failed_from_status"`
	RecoveryReasonCode    string             `json:"recovery_reason_code"`
	RecoveryFromStatus    string             `json:"recovery_from_status"`
	RecoveryTargetStatus  string             `json:"recovery_target_status"`
	RequestKey            string             `json:"request_key"`
	RequestVersion        int64              `json:"request_version"`
	OperationKey          string             `json:"operation_key"`
	OperationVersion      int64              `json:"operation_version"`
	IntentID              string             `json:"intent_id"`
	IntentVersion         int64              `json:"intent_version"`
	IntentDigest          string             `json:"intent_digest"`
	ApprovalID            string             `json:"approval_id"`
	ApprovalVersion       int64              `json:"approval_version"`
	PolicyID              string             `json:"policy_id"`
	PolicyVersion         int64              `json:"policy_version"`
	PolicyEvaluationKey   string             `json:"policy_evaluation_key"`
	PolicyEvaluationStage string             `json:"policy_evaluation_stage"`
	PolicyEvaluatedAt     pgtype.Timestamptz `json:"policy_evaluated_at"`
	RequestCreatedAt      pgtype.Timestamptz `json:"request_created_at"`
}

func (q *Queries) FindExecutionByRequestKey(ctx context.Context, arg FindExecutionByRequestKeyParams) (FindExecutionByRequestKeyRow, error) {
	row := q.db.QueryRow(ctx, findExecutionByRequestKey,
		arg.TenantID,
		arg.RequestKey,
		arg.RequestVersion,
		arg.ActorID,
	)
	var i FindExecutionByRequestKeyRow
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.RequestID,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureCode,
		&i.FailureEligibility,
		&i.FailureRecoveryTarget,
		&i.FailedFromStatus,
		&i.RecoveryReasonCode,
		&i.RecoveryFromStatus,
		&i.RecoveryTargetStatus,
		&i.RequestKey,
		&i.RequestVersion,
		&i.OperationKey,
		&i.OperationVersion,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.ApprovalID,
		&i.ApprovalVersion,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.PolicyEvaluationKey,
		&i.PolicyEvaluationStage,
		&i.PolicyEvaluatedAt,
		&i.RequestCreatedAt,
	)
	return i, err
}

const findIdentityByID = `-- name: FindIdentityByID :one
SELECT tenant_id, user_id, provider, status, lifecycle_version, created_at, updated_at, provider_subject FROM identities WHERE tenant_id = $1 AND user_id = $2 AND user_id = $3
`

type FindIdentityByIDParams struct {
	TenantID string `json:"tenant_id"`
	UserID   string `json:"user_id"`
	ActorID  string `json:"actor_id"`
}

func (q *Queries) FindIdentityByID(ctx context.Context, arg FindIdentityByIDParams) (Identity, error) {
	row := q.db.QueryRow(ctx, findIdentityByID, arg.TenantID, arg.UserID, arg.ActorID)
	var i Identity
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.LifecycleVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderSubject,
	)
	return i, err
}

const findIntentByClientRequestID = `-- name: FindIntentByClientRequestID :one
SELECT tenant_id, intent_id, intent_version, client_request_id, nonce, intent_type, user_id, identity_provider, provider_user_reference, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, network, financial, route_type, route_reference, route_version, constraint_deadline, policy_reference, created_at, expires_at, status, intent_digest, operation_key, operation_version, lifecycle_version FROM intents WHERE tenant_id=$1 AND client_request_id=$2 AND user_id=$3
`

type FindIntentByClientRequestIDParams struct {
	TenantID        string `json:"tenant_id"`
	ClientRequestID string `json:"client_request_id"`
	ActorID         string `json:"actor_id"`
}

func (q *Queries) FindIntentByClientRequestID(ctx context.Context, arg FindIntentByClientRequestIDParams) (Intent, error) {
	row := q.db.QueryRow(ctx, findIntentByClientRequestID, arg.TenantID, arg.ClientRequestID, arg.ActorID)
	var i Intent
	err := row.Scan(
		&i.TenantID,
		&i.IntentID,
		&i.IntentVersion,
		&i.ClientRequestID,
		&i.Nonce,
		&i.IntentType,
		&i.UserID,
		&i.IdentityProvider,
		&i.ProviderUserReference,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Network,
		&i.Financial,
		&i.RouteType,
		&i.RouteReference,
		&i.RouteVersion,
		&i.ConstraintDeadline,
		&i.PolicyReference,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.IntentDigest,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const findIntentByID = `-- name: FindIntentByID :one
SELECT tenant_id, intent_id, intent_version, client_request_id, nonce, intent_type, user_id, identity_provider, provider_user_reference, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, network, financial, route_type, route_reference, route_version, constraint_deadline, policy_reference, created_at, expires_at, status, intent_digest, operation_key, operation_version, lifecycle_version FROM intents WHERE tenant_id=$1 AND intent_id=$2 AND user_id=$3
`

type FindIntentByIDParams struct {
	TenantID string `json:"tenant_id"`
	IntentID string `json:"intent_id"`
	ActorID  string `json:"actor_id"`
}

func (q *Queries) FindIntentByID(ctx context.Context, arg FindIntentByIDParams) (Intent, error) {
	row := q.db.QueryRow(ctx, findIntentByID, arg.TenantID, arg.IntentID, arg.ActorID)
	var i Intent
	err := row.Scan(
		&i.TenantID,
		&i.IntentID,
		&i.IntentVersion,
		&i.ClientRequestID,
		&i.Nonce,
		&i.IntentType,
		&i.UserID,
		&i.IdentityProvider,
		&i.ProviderUserReference,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Network,
		&i.Financial,
		&i.RouteType,
		&i.RouteReference,
		&i.RouteVersion,
		&i.ConstraintDeadline,
		&i.PolicyReference,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.IntentDigest,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const findIntentByOperationKey = `-- name: FindIntentByOperationKey :one
SELECT tenant_id, intent_id, intent_version, client_request_id, nonce, intent_type, user_id, identity_provider, provider_user_reference, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, network, financial, route_type, route_reference, route_version, constraint_deadline, policy_reference, created_at, expires_at, status, intent_digest, operation_key, operation_version, lifecycle_version FROM intents WHERE tenant_id=$1 AND operation_key=$2 AND operation_version=$3 AND user_id=$4
`

type FindIntentByOperationKeyParams struct {
	TenantID         string  `json:"tenant_id"`
	OperationKey     *string `json:"operation_key"`
	OperationVersion *int64  `json:"operation_version"`
	ActorID          string  `json:"actor_id"`
}

func (q *Queries) FindIntentByOperationKey(ctx context.Context, arg FindIntentByOperationKeyParams) (Intent, error) {
	row := q.db.QueryRow(ctx, findIntentByOperationKey,
		arg.TenantID,
		arg.OperationKey,
		arg.OperationVersion,
		arg.ActorID,
	)
	var i Intent
	err := row.Scan(
		&i.TenantID,
		&i.IntentID,
		&i.IntentVersion,
		&i.ClientRequestID,
		&i.Nonce,
		&i.IntentType,
		&i.UserID,
		&i.IdentityProvider,
		&i.ProviderUserReference,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Network,
		&i.Financial,
		&i.RouteType,
		&i.RouteReference,
		&i.RouteVersion,
		&i.ConstraintDeadline,
		&i.PolicyReference,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.IntentDigest,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const findPolicyByID = `-- name: FindPolicyByID :one
SELECT tenant_id, policy_id, policy_version, name, user_id, wallet_binding_id, intent_types, rules, status, created_at, valid_from, expires_at, lifecycle_version FROM policies WHERE tenant_id=$1 AND policy_id=$2 AND policy_version=$3 AND user_id=$4
`

type FindPolicyByIDParams struct {
	TenantID      string `json:"tenant_id"`
	PolicyID      string `json:"policy_id"`
	PolicyVersion int64  `json:"policy_version"`
	ActorID       string `json:"actor_id"`
}

func (q *Queries) FindPolicyByID(ctx context.Context, arg FindPolicyByIDParams) (Policy, error) {
	row := q.db.QueryRow(ctx, findPolicyByID,
		arg.TenantID,
		arg.PolicyID,
		arg.PolicyVersion,
		arg.ActorID,
	)
	var i Policy
	err := row.Scan(
		&i.TenantID,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.Name,
		&i.UserID,
		&i.WalletBindingID,
		&i.IntentTypes,
		&i.Rules,
		&i.Status,
		&i.CreatedAt,
		&i.ValidFrom,
		&i.ExpiresAt,
		&i.LifecycleVersion,
	)
	return i, err
}

const findPolicyEvaluation = `-- name: FindPolicyEvaluation :one
SELECT tenant_id, evaluation_key, policy_id, policy_version, user_id, intent_id, intent_version, intent_digest, stage, decision, evaluated_at FROM policy_evaluations WHERE tenant_id=$1 AND evaluation_key=$2 AND user_id=$3
`

type FindPolicyEvaluationParams struct {
	TenantID      string `json:"tenant_id"`
	EvaluationKey string `json:"evaluation_key"`
	ActorID       string `json:"actor_id"`
}

func (q *Queries) FindPolicyEvaluation(ctx context.Context, arg FindPolicyEvaluationParams) (PolicyEvaluation, error) {
	row := q.db.QueryRow(ctx, findPolicyEvaluation, arg.TenantID, arg.EvaluationKey, arg.ActorID)
	var i PolicyEvaluation
	err := row.Scan(
		&i.TenantID,
		&i.EvaluationKey,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.UserID,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.Stage,
		&i.Decision,
		&i.EvaluatedAt,
	)
	return i, err
}

const findPolicyFindings = `-- name: FindPolicyFindings :many
SELECT tenant_id, evaluation_key, finding_index, rule_id, rule_type, decision, reason FROM policy_evaluation_findings WHERE tenant_id=$1 AND evaluation_key=$2 ORDER BY finding_index
`

type FindPolicyFindingsParams struct {
	TenantID      string `json:"tenant_id"`
	EvaluationKey string `json:"evaluation_key"`
}

func (q *Queries) FindPolicyFindings(ctx context.Context, arg FindPolicyFindingsParams) ([]PolicyEvaluationFinding, error) {
	rows, err := q.db.Query(ctx, findPolicyFindings, arg.TenantID, arg.EvaluationKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyEvaluationFinding{}
	for rows.Next() {
		var i PolicyEvaluationFinding
		if err := rows.Scan(
			&i.TenantID,
			&i.EvaluationKey,
			&i.FindingIndex,
			&i.RuleID,
			&i.RuleType,
			&i.Decision,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findVerificationEvidence = `-- name: FindVerificationEvidence :many
SELECT v.tenant_id, v.evidence_id, v.execution_id, v.execution_version, v.status, v.adapter_reference, v.error_code, v.observed_at FROM verification_evidence v
JOIN executions e ON e.tenant_id=v.tenant_id AND e.execution_id=v.execution_id
JOIN execution_requests r ON r.tenant_id=e.tenant_id AND r.request_id=e.request_id
WHERE v.tenant_id=$1 AND v.execution_id=$2 AND r.user_id=$3
ORDER BY v.observed_at,v.evidence_id
`

type FindVerificationEvidenceParams struct {
	TenantID    string `json:"tenant_id"`
	ExecutionID string `json:"execution_id"`
	ActorID     string `json:"actor_id"`
}

func (q *Queries) FindVerificationEvidence(ctx context.Context, arg FindVerificationEvidenceParams) ([]VerificationEvidence, error) {
	rows, err := q.db.Query(ctx, findVerificationEvidence, arg.TenantID, arg.ExecutionID, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationEvidence{}
	for rows.Next() {
		var i VerificationEvidence
		if err := rows.Scan(
			&i.TenantID,
			&i.EvidenceID,
			&i.ExecutionID,
			&i.ExecutionVersion,
			&i.Status,
			&i.AdapterReference,
			&i.ErrorCode,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWalletBindingByID = `-- name: FindWalletBindingByID :one
SELECT tenant_id, binding_id, version, user_id, provider, provider_user_reference, wallet_id, address, chain_id, network, status, verification_reference, created_at, verified_at, revoked_at FROM wallet_bindings WHERE tenant_id = $1 AND binding_id = $2 AND user_id = $3
`

type FindWalletBindingByIDParams struct {
	TenantID  string `json:"tenant_id"`
	BindingID string `json:"binding_id"`
	ActorID   string `json:"actor_id"`
}

func (q *Queries) FindWalletBindingByID(ctx context.Context, arg FindWalletBindingByIDParams) (WalletBinding, error) {
	row := q.db.QueryRow(ctx, findWalletBindingByID, arg.TenantID, arg.BindingID, arg.ActorID)
	var i WalletBinding
	err := row.Scan(
		&i.TenantID,
		&i.BindingID,
		&i.Version,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserReference,
		&i.WalletID,
		&i.Address,
		&i.ChainID,
		&i.Network,
		&i.Status,
		&i.VerificationReference,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findWalletBindingByWallet = `-- name: FindWalletBindingByWallet :one
SELECT tenant_id, binding_id, version, user_id, provider, provider_user_reference, wallet_id, address, chain_id, network, status, verification_reference, created_at, verified_at, revoked_at FROM wallet_bindings WHERE tenant_id = $1 AND chain_id = $2 AND network = $3 AND address = $4 AND user_id = $5
`

type FindWalletBindingByWalletParams struct {
	TenantID string `json:"tenant_id"`
	ChainID  string `json:"chain_id"`
	Network  string `json:"network"`
	Address  string `json:"address"`
	ActorID  string `json:"actor_id"`
}

func (q *Queries) FindWalletBindingByWallet(ctx context.Context, arg FindWalletBindingByWalletParams) (WalletBinding, error) {
	row := q.db.QueryRow(ctx, findWalletBindingByWallet,
		arg.TenantID,
		arg.ChainID,
		arg.Network,
		arg.Address,
		arg.ActorID,
	)
	var i WalletBinding
	err := row.Scan(
		&i.TenantID,
		&i.BindingID,
		&i.Version,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserReference,
		&i.WalletID,
		&i.Address,
		&i.ChainID,
		&i.Network,
		&i.Status,
		&i.VerificationReference,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.RevokedAt,
	)
	return i, err
}

const freezeIntent = `-- name: FreezeIntent :one
UPDATE intents SET status='CREATED', intent_digest=$3, operation_key=$4, operation_version=$5, lifecycle_version=$6
WHERE tenant_id=$1 AND intent_id=$2 AND status='DRAFT' AND lifecycle_version=$7 AND $6=$7+1 AND user_id=$8 RETURNING tenant_id, intent_id, intent_version, client_request_id, nonce, intent_type, user_id, identity_provider, provider_user_reference, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, network, financial, route_type, route_reference, route_version, constraint_deadline, policy_reference, created_at, expires_at, status, intent_digest, operation_key, operation_version, lifecycle_version
`

type FreezeIntentParams struct {
	TenantID           string  `json:"tenant_id"`
	IntentID           string  `json:"intent_id"`
	IntentDigest       *string `json:"intent_digest"`
	OperationKey       *string `json:"operation_key"`
	OperationVersion   *int64  `json:"operation_version"`
	LifecycleVersion   int64   `json:"lifecycle_version"`
	LifecycleVersion_2 int64   `json:"lifecycle_version_2"`
	ActorID            string  `json:"actor_id"`
}

func (q *Queries) FreezeIntent(ctx context.Context, arg FreezeIntentParams) (Intent, error) {
	row := q.db.QueryRow(ctx, freezeIntent,
		arg.TenantID,
		arg.IntentID,
		arg.IntentDigest,
		arg.OperationKey,
		arg.OperationVersion,
		arg.LifecycleVersion,
		arg.LifecycleVersion_2,
		arg.ActorID,
	)
	var i Intent
	err := row.Scan(
		&i.TenantID,
		&i.IntentID,
		&i.IntentVersion,
		&i.ClientRequestID,
		&i.Nonce,
		&i.IntentType,
		&i.UserID,
		&i.IdentityProvider,
		&i.ProviderUserReference,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Network,
		&i.Financial,
		&i.RouteType,
		&i.RouteReference,
		&i.RouteVersion,
		&i.ConstraintDeadline,
		&i.PolicyReference,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.IntentDigest,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const updateApproval = `-- name: UpdateApproval :one
UPDATE approvals SET status=$3,decision=$4,decided_at=$5,consumed_at=$6,operation_key=$7,operation_version=$8,lifecycle_version=$9
WHERE tenant_id=$1 AND approval_id=$2 AND lifecycle_version=$10 AND $9=$10+1 AND user_id=$11 RETURNING tenant_id, approval_id, approval_version, approval_request_id, intent_id, intent_version, intent_digest, user_id, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, status, decision, created_at, expires_at, decided_at, consumed_at, operation_key, operation_version, lifecycle_version
`

type UpdateApprovalParams struct {
	TenantID           string             `json:"tenant_id"`
	ApprovalID         string             `json:"approval_id"`
	Status             string             `json:"status"`
	Decision           string             `json:"decision"`
	DecidedAt          pgtype.Timestamptz `json:"decided_at"`
	ConsumedAt         pgtype.Timestamptz `json:"consumed_at"`
	OperationKey       *string            `json:"operation_key"`
	OperationVersion   *int64             `json:"operation_version"`
	LifecycleVersion   int64              `json:"lifecycle_version"`
	LifecycleVersion_2 int64              `json:"lifecycle_version_2"`
	ActorID            string             `json:"actor_id"`
}

func (q *Queries) UpdateApproval(ctx context.Context, arg UpdateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, updateApproval,
		arg.TenantID,
		arg.ApprovalID,
		arg.Status,
		arg.Decision,
		arg.DecidedAt,
		arg.ConsumedAt,
		arg.OperationKey,
		arg.OperationVersion,
		arg.LifecycleVersion,
		arg.LifecycleVersion_2,
		arg.ActorID,
	)
	var i Approval
	err := row.Scan(
		&i.TenantID,
		&i.ApprovalID,
		&i.ApprovalVersion,
		&i.ApprovalRequestID,
		&i.IntentID,
		&i.IntentVersion,
		&i.IntentDigest,
		&i.UserID,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Status,
		&i.Decision,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.ConsumedAt,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const updateExecution = `-- name: UpdateExecution :one
UPDATE executions SET status=$3,revision=$4,updated_at=$5,failure_code=$6,failure_eligibility=$7,failure_recovery_target=$8,failed_from_status=$9,recovery_reason_code=$10,recovery_from_status=$11,recovery_target_status=$12
WHERE executions.tenant_id=$1 AND executions.execution_id=$2 AND executions.revision=$13 AND $4=$13+1
  AND EXISTS (SELECT 1 FROM execution_requests r WHERE r.tenant_id=executions.tenant_id AND r.request_id=executions.request_id AND r.user_id=$14)
RETURNING tenant_id, execution_id, request_id, status, revision, created_at, updated_at, failure_code, failure_eligibility, failure_recovery_target, failed_from_status, recovery_reason_code, recovery_from_status, recovery_target_status
`

type UpdateExecutionParams struct {
	TenantID              string             `json:"tenant_id"`
	ExecutionID           string             `json:"execution_id"`
	Status                string             `json:"status"`
	Revision              int64              `json:"revision"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FailureCode           string             `json:"failure_code"`
	FailureEligibility    string             `json:"failure_eligibility"`
	FailureRecoveryTarget string             `json:"failure_recovery_target"`
	FailedFromStatus      string             `json:"failed_from_status"`
	RecoveryReasonCode    string             `json:"recovery_reason_code"`
	RecoveryFromStatus    string             `json:"recovery_from_status"`
	RecoveryTargetStatus  string             `json:"recovery_target_status"`
	Revision_2            int64              `json:"revision_2"`
	ActorID               string             `json:"actor_id"`
}

func (q *Queries) UpdateExecution(ctx context.Context, arg UpdateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, updateExecution,
		arg.TenantID,
		arg.ExecutionID,
		arg.Status,
		arg.Revision,
		arg.UpdatedAt,
		arg.FailureCode,
		arg.FailureEligibility,
		arg.FailureRecoveryTarget,
		arg.FailedFromStatus,
		arg.RecoveryReasonCode,
		arg.RecoveryFromStatus,
		arg.RecoveryTargetStatus,
		arg.Revision_2,
		arg.ActorID,
	)
	var i Execution
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.RequestID,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureCode,
		&i.FailureEligibility,
		&i.FailureRecoveryTarget,
		&i.FailedFromStatus,
		&i.RecoveryReasonCode,
		&i.RecoveryFromStatus,
		&i.RecoveryTargetStatus,
	)
	return i, err
}

const updateIntent = `-- name: UpdateIntent :one
UPDATE intents SET status=$3, lifecycle_version=$4
WHERE tenant_id=$1 AND intent_id=$2 AND status <> 'DRAFT' AND lifecycle_version=$5 AND $4=$5+1 AND user_id=$6 RETURNING tenant_id, intent_id, intent_version, client_request_id, nonce, intent_type, user_id, identity_provider, provider_user_reference, wallet_binding_id, wallet_binding_version, wallet_id, wallet_address, chain_id, network, financial, route_type, route_reference, route_version, constraint_deadline, policy_reference, created_at, expires_at, status, intent_digest, operation_key, operation_version, lifecycle_version
`

type UpdateIntentParams struct {
	TenantID           string `json:"tenant_id"`
	IntentID           string `json:"intent_id"`
	Status             string `json:"status"`
	LifecycleVersion   int64  `json:"lifecycle_version"`
	LifecycleVersion_2 int64  `json:"lifecycle_version_2"`
	ActorID            string `json:"actor_id"`
}

func (q *Queries) UpdateIntent(ctx context.Context, arg UpdateIntentParams) (Intent, error) {
	row := q.db.QueryRow(ctx, updateIntent,
		arg.TenantID,
		arg.IntentID,
		arg.Status,
		arg.LifecycleVersion,
		arg.LifecycleVersion_2,
		arg.ActorID,
	)
	var i Intent
	err := row.Scan(
		&i.TenantID,
		&i.IntentID,
		&i.IntentVersion,
		&i.ClientRequestID,
		&i.Nonce,
		&i.IntentType,
		&i.UserID,
		&i.IdentityProvider,
		&i.ProviderUserReference,
		&i.WalletBindingID,
		&i.WalletBindingVersion,
		&i.WalletID,
		&i.WalletAddress,
		&i.ChainID,
		&i.Network,
		&i.Financial,
		&i.RouteType,
		&i.RouteReference,
		&i.RouteVersion,
		&i.ConstraintDeadline,
		&i.PolicyReference,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.IntentDigest,
		&i.OperationKey,
		&i.OperationVersion,
		&i.LifecycleVersion,
	)
	return i, err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies SET status=$4,lifecycle_version=$5
WHERE tenant_id=$1 AND policy_id=$2 AND policy_version=$3 AND lifecycle_version=$6 AND $5=$6+1 AND user_id=$7 RETURNING tenant_id, policy_id, policy_version, name, user_id, wallet_binding_id, intent_types, rules, status, created_at, valid_from, expires_at, lifecycle_version
`

type UpdatePolicyParams struct {
	TenantID           string `json:"tenant_id"`
	PolicyID           string `json:"policy_id"`
	PolicyVersion      int64  `json:"policy_version"`
	Status             string `json:"status"`
	LifecycleVersion   int64  `json:"lifecycle_version"`
	LifecycleVersion_2 int64  `json:"lifecycle_version_2"`
	ActorID            string `json:"actor_id"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.TenantID,
		arg.PolicyID,
		arg.PolicyVersion,
		arg.Status,
		arg.LifecycleVersion,
		arg.LifecycleVersion_2,
		arg.ActorID,
	)
	var i Policy
	err := row.Scan(
		&i.TenantID,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.Name,
		&i.UserID,
		&i.WalletBindingID,
		&i.IntentTypes,
		&i.Rules,
		&i.Status,
		&i.CreatedAt,
		&i.ValidFrom,
		&i.ExpiresAt,
		&i.LifecycleVersion,
	)
	return i, err
}

const updateWalletBinding = `-- name: UpdateWalletBinding :one
UPDATE wallet_bindings SET version=$3, status=$4, verification_reference=$5, verified_at=$6, revoked_at=$7
WHERE tenant_id=$1 AND binding_id=$2 AND version=$8 AND $3=$8+1 AND user_id=$9 RETURNING tenant_id, binding_id, version, user_id, provider, provider_user_reference, wallet_id, address, chain_id, network, status, verification_reference, created_at, verified_at, revoked_at
`

type UpdateWalletBindingParams struct {
	TenantID              string             `json:"tenant_id"`
	BindingID             string             `json:"binding_id"`
	Version               int64              `json:"version"`
	Status                string             `json:"status"`
	VerificationReference string             `json:"verification_reference"`
	VerifiedAt            pgtype.Timestamptz `json:"verified_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
	Version_2             int64              `json:"version_2"`
	ActorID               string             `json:"actor_id"`
}

func (q *Queries) UpdateWalletBinding(ctx context.Context, arg UpdateWalletBindingParams) (WalletBinding, error) {
	row := q.db.QueryRow(ctx, updateWalletBinding,
		arg.TenantID,
		arg.BindingID,
		arg.Version,
		arg.Status,
		arg.VerificationReference,
		arg.VerifiedAt,
		arg.RevokedAt,
		arg.Version_2,
		arg.ActorID,
	)
	var i WalletBinding
	err := row.Scan(
		&i.TenantID,
		&i.BindingID,
		&i.Version,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserReference,
		&i.WalletID,
		&i.Address,
		&i.ChainID,
		&i.Network,
		&i.Status,
		&i.VerificationReference,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.RevokedAt,
	)
	return i, err
}
