// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Approval struct {
	TenantID             string             `json:"tenant_id"`
	ApprovalID           string             `json:"approval_id"`
	ApprovalVersion      int64              `json:"approval_version"`
	ApprovalRequestID    string             `json:"approval_request_id"`
	IntentID             string             `json:"intent_id"`
	IntentVersion        int64              `json:"intent_version"`
	IntentDigest         string             `json:"intent_digest"`
	UserID               string             `json:"user_id"`
	WalletBindingID      string             `json:"wallet_binding_id"`
	WalletBindingVersion int64              `json:"wallet_binding_version"`
	WalletID             string             `json:"wallet_id"`
	WalletAddress        string             `json:"wallet_address"`
	ChainID              string             `json:"chain_id"`
	Status               string             `json:"status"`
	Decision             string             `json:"decision"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	DecidedAt            pgtype.Timestamptz `json:"decided_at"`
	ConsumedAt           pgtype.Timestamptz `json:"consumed_at"`
	OperationKey         *string            `json:"operation_key"`
	OperationVersion     *int64             `json:"operation_version"`
	LifecycleVersion     int64              `json:"lifecycle_version"`
}

type AuditRecord struct {
	TenantID             string             `json:"tenant_id"`
	EventID              string             `json:"event_id"`
	EventType            string             `json:"event_type"`
	OccurredAt           pgtype.Timestamptz `json:"occurred_at"`
	ActorType            string             `json:"actor_type"`
	ActorID              string             `json:"actor_id"`
	RequestID            string             `json:"request_id"`
	TraceID              string             `json:"trace_id"`
	ResourceType         string             `json:"resource_type"`
	ResourceID           string             `json:"resource_id"`
	PreviousState        string             `json:"previous_state"`
	NewState             string             `json:"new_state"`
	SafeReasonCode       string             `json:"safe_reason_code"`
	SourceComponent      string             `json:"source_component"`
	IntentID             string             `json:"intent_id"`
	IntentVersion        int64              `json:"intent_version"`
	IntentDigest         string             `json:"intent_digest"`
	ApprovalID           string             `json:"approval_id"`
	PolicyID             string             `json:"policy_id"`
	PolicyVersion        int64              `json:"policy_version"`
	PolicyDecision       string             `json:"policy_decision"`
	PolicyEvaluationKey  string             `json:"policy_evaluation_key"`
	ExecutionID          string             `json:"execution_id"`
	ExecutionRevision    int64              `json:"execution_revision"`
	ExecutionRequestID   string             `json:"execution_request_id"`
	ExecutionRequestKey  string             `json:"execution_request_key"`
	ExecutionStatus      string             `json:"execution_status"`
	RecoveryReasonCode   string             `json:"recovery_reason_code"`
	WalletBindingID      string             `json:"wallet_binding_id"`
	WalletBindingVersion int64              `json:"wallet_binding_version"`
	UserID               string             `json:"user_id"`
	OperationKey         string             `json:"operation_key"`
	OperationVersion     int64              `json:"operation_version"`
}

type AutonomyDelegation struct {
	TenantID        string             `json:"tenant_id"`
	DelegationID    string             `json:"delegation_id"`
	Version         int64              `json:"version"`
	PrincipalUserID string             `json:"principal_user_id"`
	AgentID         string             `json:"agent_id"`
	Capabilities    []string           `json:"capabilities"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Revoked         bool               `json:"revoked"`
	NonTransitive   bool               `json:"non_transitive"`
}

type AutonomyEmergencyStop struct {
	TenantID   string             `json:"tenant_id"`
	Active     bool               `json:"active"`
	Scope      string             `json:"scope"`
	ActorID    string             `json:"actor_id"`
	ReasonCode string             `json:"reason_code"`
	ChangedAt  pgtype.Timestamptz `json:"changed_at"`
}

type AutonomyGrant struct {
	TenantID              string             `json:"tenant_id"`
	GrantID               string             `json:"grant_id"`
	Version               int64              `json:"version"`
	PrincipalUserID       string             `json:"principal_user_id"`
	WalletBindingID       string             `json:"wallet_binding_id"`
	IntentType            string             `json:"intent_type"`
	ScheduleID            *string            `json:"schedule_id"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	Paused                bool               `json:"paused"`
	Revoked               bool               `json:"revoked"`
	PerActionBaseUnits    pgtype.Numeric     `json:"per_action_base_units"`
	AggregateCapBaseUnits pgtype.Numeric     `json:"aggregate_cap_base_units"`
	RollingCapBaseUnits   pgtype.Numeric     `json:"rolling_cap_base_units"`
	RollingWindowSeconds  *int64             `json:"rolling_window_seconds"`
	StepUpBaseUnits       pgtype.Numeric     `json:"step_up_base_units"`
	AllowedRecipients     []string           `json:"allowed_recipients"`
	AllowedTokens         []string           `json:"allowed_tokens"`
	AllowedChains         []string           `json:"allowed_chains"`
}

type AutonomyOccurrence struct {
	TenantID        string             `json:"tenant_id"`
	OccurrenceID    string             `json:"occurrence_id"`
	OccurrenceKey   string             `json:"occurrence_key"`
	ScheduleID      string             `json:"schedule_id"`
	ScheduleVersion int64              `json:"schedule_version"`
	ScheduleDigest  string             `json:"schedule_digest"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	Status          string             `json:"status"`
	GrantID         string             `json:"grant_id"`
	GrantVersion    int64              `json:"grant_version"`
	IntentID        *string            `json:"intent_id"`
	ApprovalID      *string            `json:"approval_id"`
	ExecutionID     *string            `json:"execution_id"`
	LeaseOwner      *string            `json:"lease_owner"`
	LeaseUntil      pgtype.Timestamptz `json:"lease_until"`
	Fence           int64              `json:"fence"`
	ReasonCode      string             `json:"reason_code"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AutonomySchedule struct {
	TenantID             string             `json:"tenant_id"`
	ScheduleID           string             `json:"schedule_id"`
	Version              int64              `json:"version"`
	UserID               string             `json:"user_id"`
	AgentID              string             `json:"agent_id"`
	WalletBindingID      string             `json:"wallet_binding_id"`
	WalletBindingVersion int64              `json:"wallet_binding_version"`
	IntentType           string             `json:"intent_type"`
	GrantID              string             `json:"grant_id"`
	GrantVersion         int64              `json:"grant_version"`
	DelegationID         string             `json:"delegation_id"`
	DelegationVersion    int64              `json:"delegation_version"`
	Status               string             `json:"status"`
	SpecDigest           string             `json:"spec_digest"`
	ScheduleDigest       string             `json:"schedule_digest"`
	Timezone             string             `json:"timezone"`
	StartAt              pgtype.Timestamptz `json:"start_at"`
	EndAt                pgtype.Timestamptz `json:"end_at"`
	MaxRecipients        int32              `json:"max_recipients"`
	Recurrence           string             `json:"recurrence"`
	MissedRun            string             `json:"missed_run"`
	Concurrency          string             `json:"concurrency"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AutonomySpendReservation struct {
	TenantID        string             `json:"tenant_id"`
	GrantID         string             `json:"grant_id"`
	GrantVersion    int64              `json:"grant_version"`
	OccurrenceID    string             `json:"occurrence_id"`
	AmountBaseUnits pgtype.Numeric     `json:"amount_base_units"`
	ReservedAt      pgtype.Timestamptz `json:"reserved_at"`
	State           string             `json:"state"`
}

type Execution struct {
	TenantID              string             `json:"tenant_id"`
	ExecutionID           string             `json:"execution_id"`
	RequestID             string             `json:"request_id"`
	Status                string             `json:"status"`
	Revision              int64              `json:"revision"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FailureCode           string             `json:"failure_code"`
	FailureEligibility    string             `json:"failure_eligibility"`
	FailureRecoveryTarget string             `json:"failure_recovery_target"`
	FailedFromStatus      string             `json:"failed_from_status"`
	RecoveryReasonCode    string             `json:"recovery_reason_code"`
	RecoveryFromStatus    string             `json:"recovery_from_status"`
	RecoveryTargetStatus  string             `json:"recovery_target_status"`
}

type ExecutionRequest struct {
	TenantID              string             `json:"tenant_id"`
	RequestID             string             `json:"request_id"`
	RequestKey            string             `json:"request_key"`
	RequestVersion        int64              `json:"request_version"`
	ExecutionID           string             `json:"execution_id"`
	OperationKey          string             `json:"operation_key"`
	OperationVersion      int64              `json:"operation_version"`
	IntentID              string             `json:"intent_id"`
	IntentVersion         int64              `json:"intent_version"`
	IntentDigest          string             `json:"intent_digest"`
	ApprovalID            string             `json:"approval_id"`
	ApprovalVersion       int64              `json:"approval_version"`
	UserID                string             `json:"user_id"`
	PolicyID              string             `json:"policy_id"`
	PolicyVersion         int64              `json:"policy_version"`
	PolicyEvaluationKey   string             `json:"policy_evaluation_key"`
	PolicyEvaluationStage string             `json:"policy_evaluation_stage"`
	PolicyEvaluatedAt     pgtype.Timestamptz `json:"policy_evaluated_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type ExecutionRevision struct {
	TenantID    string             `json:"tenant_id"`
	ExecutionID string             `json:"execution_id"`
	Revision    int64              `json:"revision"`
	Status      string             `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ExecutionRuntimeWork struct {
	TenantID          string             `json:"tenant_id"`
	ExecutionID       string             `json:"execution_id"`
	NextRunAt         pgtype.Timestamptz `json:"next_run_at"`
	LeaseOwner        string             `json:"lease_owner"`
	LeaseExpiresAt    pgtype.Timestamptz `json:"lease_expires_at"`
	FencingToken      int64              `json:"fencing_token"`
	SubmissionStarted bool               `json:"submission_started"`
}

type Identity struct {
	TenantID         string             `json:"tenant_id"`
	UserID           string             `json:"user_id"`
	Provider         string             `json:"provider"`
	Status           string             `json:"status"`
	LifecycleVersion int64              `json:"lifecycle_version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ProviderSubject  string             `json:"provider_subject"`
}

type Intent struct {
	TenantID              string             `json:"tenant_id"`
	IntentID              string             `json:"intent_id"`
	IntentVersion         int64              `json:"intent_version"`
	ClientRequestID       string             `json:"client_request_id"`
	Nonce                 string             `json:"nonce"`
	IntentType            string             `json:"intent_type"`
	UserID                string             `json:"user_id"`
	IdentityProvider      string             `json:"identity_provider"`
	ProviderUserReference string             `json:"provider_user_reference"`
	WalletBindingID       string             `json:"wallet_binding_id"`
	WalletBindingVersion  int64              `json:"wallet_binding_version"`
	WalletID              string             `json:"wallet_id"`
	WalletAddress         string             `json:"wallet_address"`
	ChainID               string             `json:"chain_id"`
	Network               string             `json:"network"`
	Financial             []byte             `json:"financial"`
	RouteType             string             `json:"route_type"`
	RouteReference        string             `json:"route_reference"`
	RouteVersion          int64              `json:"route_version"`
	ConstraintDeadline    pgtype.Timestamptz `json:"constraint_deadline"`
	PolicyReference       string             `json:"policy_reference"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	Status                string             `json:"status"`
	IntentDigest          *string            `json:"intent_digest"`
	OperationKey          *string            `json:"operation_key"`
	OperationVersion      *int64             `json:"operation_version"`
	LifecycleVersion      int64              `json:"lifecycle_version"`
}

type Policy struct {
	TenantID         string             `json:"tenant_id"`
	PolicyID         string             `json:"policy_id"`
	PolicyVersion    int64              `json:"policy_version"`
	Name             string             `json:"name"`
	UserID           string             `json:"user_id"`
	WalletBindingID  *string            `json:"wallet_binding_id"`
	IntentTypes      []string           `json:"intent_types"`
	Rules            []byte             `json:"rules"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LifecycleVersion int64              `json:"lifecycle_version"`
}

type PolicyEvaluation struct {
	TenantID      string             `json:"tenant_id"`
	EvaluationKey string             `json:"evaluation_key"`
	PolicyID      string             `json:"policy_id"`
	PolicyVersion int64              `json:"policy_version"`
	UserID        string             `json:"user_id"`
	IntentID      string             `json:"intent_id"`
	IntentVersion int64              `json:"intent_version"`
	IntentDigest  string             `json:"intent_digest"`
	Stage         string             `json:"stage"`
	Decision      string             `json:"decision"`
	EvaluatedAt   pgtype.Timestamptz `json:"evaluated_at"`
}

type PolicyEvaluationFinding struct {
	TenantID      string `json:"tenant_id"`
	EvaluationKey string `json:"evaluation_key"`
	FindingIndex  int32  `json:"finding_index"`
	RuleID        string `json:"rule_id"`
	RuleType      string `json:"rule_type"`
	Decision      string `json:"decision"`
	Reason        string `json:"reason"`
}

type SchemaMigration struct {
	Version   int64              `json:"version"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type Tenant struct {
	TenantID  string             `json:"tenant_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type VerificationEvidence struct {
	TenantID         string             `json:"tenant_id"`
	EvidenceID       int64              `json:"evidence_id"`
	ExecutionID      string             `json:"execution_id"`
	ExecutionVersion int64              `json:"execution_version"`
	Status           string             `json:"status"`
	AdapterReference string             `json:"adapter_reference"`
	ErrorCode        string             `json:"error_code"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
}

type WalletBinding struct {
	TenantID              string             `json:"tenant_id"`
	BindingID             string             `json:"binding_id"`
	Version               int64              `json:"version"`
	UserID                string             `json:"user_id"`
	Provider              string             `json:"provider"`
	ProviderUserReference string             `json:"provider_user_reference"`
	WalletID              string             `json:"wallet_id"`
	Address               string             `json:"address"`
	ChainID               string             `json:"chain_id"`
	Network               string             `json:"network"`
	Status                string             `json:"status"`
	VerificationReference string             `json:"verification_reference"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	VerifiedAt            pgtype.Timestamptz `json:"verified_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
}

type WalletBindingVersion struct {
	TenantID              string             `json:"tenant_id"`
	BindingID             string             `json:"binding_id"`
	Version               int64              `json:"version"`
	UserID                string             `json:"user_id"`
	Provider              string             `json:"provider"`
	ProviderUserReference string             `json:"provider_user_reference"`
	WalletID              string             `json:"wallet_id"`
	Address               string             `json:"address"`
	ChainID               string             `json:"chain_id"`
	Network               string             `json:"network"`
	Status                string             `json:"status"`
	VerificationReference string             `json:"verification_reference"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	VerifiedAt            pgtype.Timestamptz `json:"verified_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
}
