// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package dbsqlc

import (
	"context"
	"time"
)

const createOAuthClient = `-- name: CreateOAuthClient :exec
INSERT INTO oauth_clients(client_id,name,client_type,auth_method,status,redirect_uris,scopes,resources) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type CreateOAuthClientParams struct {
	ClientID     string   `json:"client_id"`
	Name         string   `json:"name"`
	ClientType   string   `json:"client_type"`
	AuthMethod   string   `json:"auth_method"`
	Status       string   `json:"status"`
	RedirectUris []string `json:"redirect_uris"`
	Scopes       []string `json:"scopes"`
	Resources    []string `json:"resources"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error {
	_, err := q.db.Exec(ctx, createOAuthClient,
		arg.ClientID,
		arg.Name,
		arg.ClientType,
		arg.AuthMethod,
		arg.Status,
		arg.RedirectUris,
		arg.Scopes,
		arg.Resources,
	)
	return err
}

const createOAuthTransaction = `-- name: CreateOAuthTransaction :exec
INSERT INTO oauth_transactions(transaction_id,client_id,redirect_uri,resource,scope,challenge,state,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type CreateOAuthTransactionParams struct {
	TransactionID string    `json:"transaction_id"`
	ClientID      string    `json:"client_id"`
	RedirectUri   string    `json:"redirect_uri"`
	Resource      string    `json:"resource"`
	Scope         string    `json:"scope"`
	Challenge     string    `json:"challenge"`
	State         string    `json:"state"`
	CreatedAt     time.Time `json:"created_at"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) CreateOAuthTransaction(ctx context.Context, arg CreateOAuthTransactionParams) error {
	_, err := q.db.Exec(ctx, createOAuthTransaction,
		arg.TransactionID,
		arg.ClientID,
		arg.RedirectUri,
		arg.Resource,
		arg.Scope,
		arg.Challenge,
		arg.State,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const findOAuthClient = `-- name: FindOAuthClient :one
SELECT client_id, name, client_type, auth_method, status, redirect_uris, scopes, resources, registered_at FROM oauth_clients WHERE client_id=$1
`

func (q *Queries) FindOAuthClient(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, findOAuthClient, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.Name,
		&i.ClientType,
		&i.AuthMethod,
		&i.Status,
		&i.RedirectUris,
		&i.Scopes,
		&i.Resources,
		&i.RegisteredAt,
	)
	return i, err
}

const findOAuthTransaction = `-- name: FindOAuthTransaction :one
SELECT transaction_id, client_id, redirect_uri, resource, scope, challenge, state, created_at, expires_at, completed_at FROM oauth_transactions WHERE transaction_id=$1 AND completed_at IS NULL
`

func (q *Queries) FindOAuthTransaction(ctx context.Context, transactionID string) (OauthTransaction, error) {
	row := q.db.QueryRow(ctx, findOAuthTransaction, transactionID)
	var i OauthTransaction
	err := row.Scan(
		&i.TransactionID,
		&i.ClientID,
		&i.RedirectUri,
		&i.Resource,
		&i.Scope,
		&i.Challenge,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CompletedAt,
	)
	return i, err
}

const validateOAuthAccessToken = `-- name: ValidateOAuthAccessToken :one
SELECT a.token_digest, a.issuer, a.resource, a.tenant_id, a.user_id, a.client_id, a.consent_id, a.session_id, a.scope, a.identity_issuer, a.subject, a.issued_at, a.expires_at, a.revoked_at FROM oauth_access_tokens a
JOIN oauth_clients c ON c.client_id=a.client_id
JOIN oauth_consents u ON u.tenant_id=a.tenant_id AND u.user_id=a.user_id AND u.consent_id=a.consent_id AND u.client_id=a.client_id AND u.resource=a.resource AND u.scope=a.scope AND u.session_id=a.session_id
JOIN oauth_sessions s ON s.tenant_id=a.tenant_id AND s.user_id=a.user_id AND s.session_id=a.session_id
JOIN identities i ON i.tenant_id=a.tenant_id AND i.user_id=a.user_id AND i.provider=a.identity_issuer AND i.provider_subject=a.subject
WHERE a.token_digest=$1 AND a.issuer='https://connect.wizpay.xyz' AND a.resource='https://mcp.wizpay.xyz/mcp'
AND a.revoked_at IS NULL AND a.issued_at<=$2 AND a.expires_at>$2
AND c.status='ACTIVE' AND c.client_type='public' AND c.auth_method='none'
AND a.scope=ANY(c.scopes) AND a.resource=ANY(c.resources)
AND u.revoked_at IS NULL AND u.created_at<=$2 AND u.expires_at>$2
AND NOT EXISTS(SELECT 1 FROM oauth_consent_wallets w WHERE w.tenant_id=u.tenant_id AND w.user_id=u.user_id AND w.consent_id=u.consent_id)
AND s.revoked_at IS NULL AND s.expires_at>$2 AND i.status='ACTIVE'
`

type ValidateOAuthAccessTokenParams struct {
	TokenDigest string    `json:"token_digest"`
	IssuedAt    time.Time `json:"issued_at"`
}

func (q *Queries) ValidateOAuthAccessToken(ctx context.Context, arg ValidateOAuthAccessTokenParams) (OauthAccessToken, error) {
	row := q.db.QueryRow(ctx, validateOAuthAccessToken, arg.TokenDigest, arg.IssuedAt)
	var i OauthAccessToken
	err := row.Scan(
		&i.TokenDigest,
		&i.Issuer,
		&i.Resource,
		&i.TenantID,
		&i.UserID,
		&i.ClientID,
		&i.ConsentID,
		&i.SessionID,
		&i.Scope,
		&i.IdentityIssuer,
		&i.Subject,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
