// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	AppendAudit(ctx context.Context, arg AppendAuditParams) error
	AppendVerificationEvidence(ctx context.Context, arg AppendVerificationEvidenceParams) (int64, error)
	ClaimExecutionWork(ctx context.Context, arg ClaimExecutionWorkParams) (ExecutionRuntimeWork, error)
	ClaimNextExecutionWork(ctx context.Context, arg ClaimNextExecutionWorkParams) (ExecutionRuntimeWork, error)
	CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error)
	CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error)
	CreateExecutionRequest(ctx context.Context, arg CreateExecutionRequestParams) (ExecutionRequest, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error)
	CreateIntent(ctx context.Context, arg CreateIntentParams) (Intent, error)
	CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error)
	CreatePolicyEvaluation(ctx context.Context, arg CreatePolicyEvaluationParams) (PolicyEvaluation, error)
	CreatePolicyFinding(ctx context.Context, arg CreatePolicyFindingParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateWalletBinding(ctx context.Context, arg CreateWalletBindingParams) (WalletBinding, error)
	FindApplicablePolicies(ctx context.Context, arg FindApplicablePoliciesParams) ([]FindApplicablePoliciesRow, error)
	FindApprovalByID(ctx context.Context, arg FindApprovalByIDParams) (Approval, error)
	FindApprovalByIntent(ctx context.Context, arg FindApprovalByIntentParams) (Approval, error)
	FindAuditByResource(ctx context.Context, arg FindAuditByResourceParams) ([]AuditRecord, error)
	FindExecutionByID(ctx context.Context, arg FindExecutionByIDParams) (FindExecutionByIDRow, error)
	FindExecutionByOperationKey(ctx context.Context, arg FindExecutionByOperationKeyParams) (FindExecutionByOperationKeyRow, error)
	FindExecutionByRequestKey(ctx context.Context, arg FindExecutionByRequestKeyParams) (FindExecutionByRequestKeyRow, error)
	FindExecutionOwner(ctx context.Context, arg FindExecutionOwnerParams) (FindExecutionOwnerRow, error)
	FindIdentityByID(ctx context.Context, arg FindIdentityByIDParams) (Identity, error)
	FindIntentByClientRequestID(ctx context.Context, arg FindIntentByClientRequestIDParams) (Intent, error)
	FindIntentByID(ctx context.Context, arg FindIntentByIDParams) (Intent, error)
	FindIntentByOperationKey(ctx context.Context, arg FindIntentByOperationKeyParams) (Intent, error)
	FindPolicyByID(ctx context.Context, arg FindPolicyByIDParams) (Policy, error)
	FindPolicyEvaluation(ctx context.Context, arg FindPolicyEvaluationParams) (PolicyEvaluation, error)
	FindPolicyFindings(ctx context.Context, arg FindPolicyFindingsParams) ([]PolicyEvaluationFinding, error)
	FindVerificationEvidence(ctx context.Context, arg FindVerificationEvidenceParams) ([]VerificationEvidence, error)
	FindWalletBindingByID(ctx context.Context, arg FindWalletBindingByIDParams) (WalletBinding, error)
	FindWalletBindingByWallet(ctx context.Context, arg FindWalletBindingByWalletParams) (WalletBinding, error)
	FreezeIntent(ctx context.Context, arg FreezeIntentParams) (Intent, error)
	ListApprovals(ctx context.Context, arg ListApprovalsParams) ([]Approval, error)
	MarkSubmissionStarted(ctx context.Context, arg MarkSubmissionStartedParams) (ExecutionRuntimeWork, error)
	ReleaseExecutionWork(ctx context.Context, arg ReleaseExecutionWorkParams) (int64, error)
	ResetSubmissionStarted(ctx context.Context, arg ResetSubmissionStartedParams) (int64, error)
	UpdateApproval(ctx context.Context, arg UpdateApprovalParams) (Approval, error)
	UpdateExecution(ctx context.Context, arg UpdateExecutionParams) (Execution, error)
	UpdateIntent(ctx context.Context, arg UpdateIntentParams) (Intent, error)
	UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error)
	UpdateWalletBinding(ctx context.Context, arg UpdateWalletBindingParams) (WalletBinding, error)
	ValidateExecutionClaim(ctx context.Context, arg ValidateExecutionClaimParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
